CREATE TABLE "Category" (
    "id" BIGSERIAL NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "nameLat" VARCHAR(255) NOT NULL,
    "parentId" INTEGER[],
    "sort" INTEGER,
    "tree" INTEGER[],
    "autogenerated" BOOLEAN
);

ALTER TABLE "Category" ADD CONSTRAINT "pkCategory" PRIMARY KEY ("id");

CREATE TABLE "Product" (
    "id" BIGSERIAL NOT NULL,
    "article" VARCHAR(255) NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "description" TEXT,
    "price" DECIMAL(10, 2),
    "attributes" JSONB,
    "brand" VARCHAR(255),
    "branding" VARCHAR(255)[],
    "categories" INTEGER[],
    "dominantColor" VARCHAR(7),
    "images" JSONB,
    "isParent" BOOLEAN,
    "packages" JSONB,
    "productsAttachment" VARCHAR(255)[],
    "rating" INTEGER,
    "sizes" JSONB,
    "source" INTEGER,
    "autogenerated" BOOLEAN
);

ALTER TABLE "Product" ADD CONSTRAINT "pkProduct" PRIMARY KEY ("id");
ALTER TABLE "Product" ADD CONSTRAINT "fkCategory" FOREIGN KEY ("categories") REFERENCES "Category" ("id");
